# Generated by Django 4.2.16 on 2026-09-23 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_remove_candidate_bio_candidate_party_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='potrait',
            new_name='portrait',
        ),
    ]
