# Generated by Django 4.2.16 on 2026-09-27 10:30

from django.db import migrations, models
import elections.models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_electionsettings_registrationrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationrequest',
            name='token',
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='approval_code',
            field=models.CharField(default=elections.models.generate_5_digit_code, max_length=5),
        ),
    ]
