# Generated by Django 4.2.16 on 2026-09-27 22:02

from django.db import migrations, models
import elections.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0007_remove_registrationrequest_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='admin_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='approval_code',
            field=models.CharField(default=elections.models.generate_5_digit_code, editable=False, max_length=5),
        ),
    ]
