# Generated by Django 4.2.16 on 2026-09-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0008_registrationrequest_admin_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
