# Generated by Django 4.2.16 on 2026-10-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0009_vote_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationrequest',
            name='username',
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='student_id',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
